FrontendApplication/eRecruitment.Sita.Web/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eRecruitment.Sita.Web.Models;
using Microsoft.AspNet.Identity;

namespace eRecruitment.Sita.Web.Controllers
{
    public class ApplicationsController : Controller
    {
        eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db = new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
        eRecruitmentDataAccess _dal = new eRecruitmentDataAccess();
        //eRecruitment.Sita.Web.Notification.SendNotification notify = new eRecruitment.Sita.Web.Notification.SendNotification();
        Notification notify = new Notification();
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Applications
        public ActionResult Index()
        {
            string userid = User.Identity.GetUserId();
            ViewBag.ApplicationList = _dal.GetApplicationsList();
            return View();
        }

        //View Received Application Detailes
        public ActionResult ViewReceivedApplicationDetailes(int id)
        {
            ViewBag.Gender = _dal.GetGenderList();
            string useri = User.Identity.GetUserId();
            var Ap = _dal.ApplicationDetailes(id);
            ViewBag.Vacancy = Ap;
            return View(Ap);

        }

        //DownLoad Attachments
        [HttpGet]
        public FileResult DownLoadAttachements(int id)
        {
            var doc = _db.Attachments.Where(x => x.AttachmentID == id).FirstOrDefault();
            return File(doc.fileData.ToArray(), doc.contentType, doc.fileName);
        }

        //Shortlist Candidate
        public ActionResult shortlist(int id)
        {
            //2 is Shortlisted
            _dal.UpdateApplicationStatus(2, Convert.ToInt16(id));
            return RedirectToAction("Index");
        }
   
    }
}

FrontendApplication/eRecruitment.Sita.Web/Views/Applications/Index.cshtml
@model IEnumerable<eRecruitment.Sita.Web.Models.CandidateVacancyApplication>

@{
    ViewBag.Title = "ReceivedApplication";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Received Application
        @*<small>&nbsp;</small>*@
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Applications</a></li>
        <li class="active">Applications List</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <div class="pull-left">
               <br>
            </div>
            @*<h3 class="box-title"><input type="button" class="btn btn-primary btn-sm" value="Add New Vacancy" /></h3>*@
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" disabled class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="box">
               <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>FirstName </th>
                                <th>Surname</th>
                                <th>Date Applied</th>
                                <th>Job Applied For</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @if (@ViewBag.ApplicationList != null)
                            {
                                foreach (var item in ViewBag.ApplicationList)
                                {
                                    <tr>
                                        <td>@item.FirstName</td>
                                        <td>@item.Surname</td>
                                        <td>@item.ApplicationDate</td>
                                        <td>@item.JobTitle</td>
                                        <td>@item.status</td>
                                        <td>@item.Location</td>
                                    
                                        <td>
                                           <div class="btn-group">
                                                <button type="button" class="btn btn-success">Action</button>
                                                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                </button>

                                                    <ul class="dropdown-menu" role="menu">

                                                        <a href="@Url.Action("ViewReceivedApplicationDetailes", "Applications", new { id = @item.ApplicationID })"><span class="fa fa-send success" style="color:green"></span> Detailes</a>

                                                    </ul>                                                
                                            </div>
                                        </td>
                                   </tr>

                                }
                            }


                       </tbody>          
                    </table>                
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            @*Footer*@
            &nbsp;
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
</section>

FrontendApplication/eRecruitment.Sita.Web/Views/Applications/ViewReceivedApplicationDetailes.cshtml
@model IEnumerable<eRecruitment.Sita.Web.Models.CandidateVacancyApplication>
@{
    ViewBag.Title = "ViewReceivedApplicationDetailes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using System.Data.Linq
@{
    eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db =
        new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
}
<section class="content-header">
    <h1>
        &nbsp;
        @*Blank page*@
        @*<small>it all starts here</small>*@
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Application</a></li>
        <li class="active">Application Detailes</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Application Detailes</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            @foreach (var item in Model)
            {
                using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.ReferenceNo, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Applicant Summary</label>                                 
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.ReferenceNo, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>First Name</label>
                                    
                                    @Html.TextBoxFor(m => @item.FirstName, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Surname</label>
                                    @Html.TextBoxFor(m => @item.Surname, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Identinty No</label>
                                    @Html.TextBoxFor(m => @item.IDNumber, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Date of Birth</label>
                               
                                    @Html.TextBoxFor(m => @item.DateofBirth, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Gender</label>
                                    @Html.DropDownListFor(m => @item.Gender, new SelectList(ViewBag.Gender, "GenderID", "Gender", @item.Gender), "--Select Organisation Type--", new { @class = "form-control", disabled = "disabled", @readonly = "readonly", tabindex = 5 })
                                   
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                        
                                <div class="col-md-12">
                                    <label>Vacancy Summary</label>                           
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Reference No</label>
                                    @Html.TextBoxFor(m => @item.Refno, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Job Title</label>
                                    @Html.TextBoxFor(m => @item.JobTitle, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                    @*@Html.TextBoxFor(m => m.EmploymentTypeID, new { @class = "form-control" })*@
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Job Level</label>
                                    @Html.TextBoxFor(m => @item.Joblevel, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                    @*@Html.TextBoxFor(m => m.EmploymentTypeID, new { @class = "form-control" })*@
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Salary</label>
                                    @Html.TextBoxFor(m => @item.Salary, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>                  
                            <div class="form-group">
                                @*@Html.LabelFor(m => m.VacancyName, new { @class = "col-md-2 control-label" })*@
                                <div class="col-md-12">
                                    <label>Location</label>
                                    @Html.TextBoxFor(m => @item.Location, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                                </div>
                            </div>                     
                        </div>
                    </div>
                    <div class="row">
                       <br />
                        <br /><div class="clearfix"></div><br />
                        <div class="col-md-12">
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Supporting Attachments</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form">
                                    <div class="box-body">
                                        @{
                                            int proID = @item.profileID;
                                            var doc = _db.Attachments.Where(x => x.profileID == proID).ToList();
                                            <table id="example1" class="table table-bordered table-striped">
                                                <thead>
                                                    <tr>
                                                        <th class="col-md-11">Document Name</th>
                                                        <th class="col-md-1">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var d in doc)
                                                    {
                                                        <tr>
                                                            <td>@d.fileName</td>
                                                            <td>
                                                                <div class="hidden-sm hidden-xs btn-group">
                                                                    <a class="btn btn-xs btn-success btn-xs" href='@Url.Action("DownLoadAttachements", "Applications", new { id = @d.attachmentID})' data-toggle="tooltip" data-placement="left" title="Download file">
                                                                        <i class="ace-icon fa fa-download bigger-120"> Download</i>
                                                                    </a>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>

                                        }

                                    </div>
                                    <!-- /.box-body -->

                                </form>
                            </div>


                        </div>
                        <div class="clearfix"></div><br />
                        <div class="col-md-12 pull-right">
                            <a href="@Url.Action("shortlist", "Applications",new { id = @item.ApplicationID })"class="btn btn-success btn-sm">
                                <span class="fa fa-check" aria-hidden="true"></span>
                                ShortList Candidate
                            </a>
                            <a href="@Url.Action("Index", "Applications")" class="btn btn-info btn-sm">
                                <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                Back to List
                            </a>

                        </div>
                    </div>
                                                }


                                            }
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            &nbsp;
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->