FrontendApplication/eRecruitment.Sita.Web/Controllers/CareerCenterController.cs
using eRecruitment.Sita.Web.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Data;
using System.IO;
using System.Text;

namespace eRecruitment.Sita.Web.Controllers
{
    public class CareerCenterController : Controller
    {
        eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db = new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
        eRecruitmentDataAccess _dal = new eRecruitmentDataAccess();

        // GET: CareerCenter
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MyProfile(string tabname)
        {
            string Userid = User.Identity.GetUserId();
            int profileID = 0;
            profileID = _dal.GetProfileID(User.Identity.GetUserId());

            ViewBag.Race = _dal.GetRaceList();
            ViewBag.Gender = _dal.GetGenderList();
            ViewBag.Province = _dal.GetProvinceList();
            ViewBag.YesorNo = _dal.GetYesorNoList();
            ViewBag.Country = _dal.GetCountryList();
            ViewBag.Disability = _dal.GetDisabilityList();
            ViewBag.QualificationType = _dal.GetQualificationTypeList();
            ViewBag.Language = _dal.GetLanguageList();
            ViewBag.LanguageProficiency = _dal.GetLanguageProficiencyList();
            ViewBag.SkillProficiency = _dal.GetSkillProficiencyList();
            ViewBag.Skills = _dal.GetSkillsList();

            //ViewBag.Education = _dal.GetQualificationByProfileID(Userid);
            ViewBag.WorkHistory = _dal.GetWorkHistoryByProfileID(Userid);
            ViewBag.References = _dal.GetReferenceByProfileID(Userid);
            ViewBag.Attachments = _dal.GetAttachmentByProfileID(Userid);
            ViewBag.SkillsForProfile = _dal.GetSkillsByProfileID(profileID);
            ViewBag.LanguagesForProfile = _dal.GetLanguagesByProfileID(profileID);
            ViewBag.CommunicationMethod = _dal.GetMethodOfCommunication();

            var P = new List<ProfileModel>();
            using (eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db = new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext())
            {
                var prof = _db.tblProfiles.Where(x => x.UserID == Userid).ToList();

                foreach (var d in prof)
                {
                    ProfileModel e = new ProfileModel();
                    e.IDNumber = Convert.ToString(d.IDNumber);
                    e.Surname = Convert.ToString(d.Surname);
                    e.FirstName = Convert.ToString(d.FirstName);
                    e.DateOfBirth = Convert.ToDateTime(d.DateOfBirth);
                    e.fkRaceID = Convert.ToInt16(d.fkRaceID);
                    e.fkGenderID = Convert.ToInt16(d.fkGenderID);
                    e.CellNo = Convert.ToString(d.CellNo);
                    e.AlternativeNo = Convert.ToString(d.AlternativeNo);
                    e.EmailAddress = Convert.ToString(d.EmailAddress);
                    e.UnitNo = Convert.ToString(d.UnitNo);
                    e.ComplexName = Convert.ToString(d.ComplexName);
                    e.StreetNo = Convert.ToString(d.StreetNo);
                    e.StreetName = Convert.ToString(d.StreetName);
                    e.SuburbName = Convert.ToString(d.SuburbName);
                    e.City = Convert.ToString(d.City);
                    e.PostalCode = Convert.ToString(d.PostalCode);
                    e.fkDisabilityID = Convert.ToInt16(d.fkDisabilityID);
                    e.NatureOfDisability = Convert.ToInt16(d.NatureOfDisability);
                    e.SACitizen = Convert.ToInt16(d.SACitizen);
                    e.fkNationalityID = Convert.ToInt16(d.fkNationalityID);
                    e.fkProvinceID = Convert.ToInt16(d.fkProvinceID);
                    e.fkWorkPermitID = Convert.ToInt16(d.fkWorkPermitID);
                    e.WorkPermitNo = Convert.ToString(d.WorkPermitNo);
                    e.pkCriminalOffenseID = Convert.ToInt16(d.pkCriminalOffenseID);
                    e.fkLanguageForCorrespondenceID = Convert.ToInt16(d.fkLanguageForCorrespondenceID);
                    e.TelNoDuringWorkingHours = Convert.ToString(d.TelNoDuringWorkingHours);
                    e.MethodOfCommunicationID = Convert.ToInt16(d.MethodOfCommunicationID);
                    e.CorrespondanceDetails = Convert.ToString(d.CorrespondanceDetails);
                    //e.TermsAndConditions = Convert.ToBoolean(d.TermsAndConditions);
                    P.Add(e);
                }
            }
            return View(P);

        }

        public ActionResult MyApplications()
        {
            ViewBag.MyApplications = _dal.GetCandidateVacancyApplications(User.Identity.GetUserId());
            return View();
        }

        [HttpPost]
        public ActionResult UpdateProfile(ProfileModel item, HttpPostedFileBase postedCV, HttpPostedFileBase postedID)
        {
            ViewBag.CommunicationMethod = _dal.GetMethodOfCommunication();
            string Userid;
            Userid = User.Identity.GetUserId();

            string IDNumber = item.IDNumber;
            string Surname = item.Surname;
            string FirstName = item.FirstName;
            string DateOfBirth = Convert.ToString(item.DateOfBirth);
            int fkRaceID = Convert.ToInt16(item.fkRaceID);
            int fkGenderID = Convert.ToInt16(item.fkGenderID);
            string CellNo = item.CellNo;
            string AlternativeNo = item.AlternativeNo;
            string EmailAddress = item.EmailAddress;
            string UnitNo = item.UnitNo;
            string ComplexName = item.ComplexName;
            string StreetNo = item.StreetNo;
            string StreetName = item.StreetName;
            string SuburbName = item.SuburbName;
            string City = item.City;
            string PostalCode = item.PostalCode;
            int fkDisabilityID = Convert.ToInt16(item.fkDisabilityID);
            int NatureOfDisability = Convert.ToInt16(item.NatureOfDisability);
            string OtherNatureOfDisability = item.OtherNatureOfDisability;
            int SACitizen = Convert.ToInt16(item.SACitizen);
            int fkNationalityID = Convert.ToInt16(item.fkNationalityID);
            int fkProvinceID = Convert.ToInt16(item.fkProvinceID);
            int fkWorkPermitID = Convert.ToInt16(item.fkWorkPermitID);
            string WorkPermitNo = item.WorkPermitNo;
            int pkCriminalOffenseID = Convert.ToInt16(item.pkCriminalOffenseID);
            int fkLanguageForCorrespondenceID = Convert.ToInt16(item.fkLanguageForCorrespondenceID);
            string TelNoDuringWorkingHours = item.TelNoDuringWorkingHours;
            int MethodOfCommunicationID = Convert.ToInt16(item.MethodOfCommunicationID);
            string CorrespondanceDetails = item.CorrespondanceDetails;
            int? ProfessionallyRegisteredID = item.ProfessionallyRegisteredID;
            string RegistrationDate = Convert.ToString(item.RegistrationDate);
            string RegistrationNumber = item.RegistrationNumber;
            string RegistrationBody = item.RegistrationBody;
            int? PreviouslyEmployedPS = item.PreviouslyEmployedPS;
            string ReEmployment = item.ReEmploy;
            string PreviouslyEmployedDepartment = item.PreviouslyEmployedDepartment;
            int DriversLicenseID = Convert.ToInt16(item.DriversLicenseID);
            int MatricID = Convert.ToInt16(item.MatricID);
            int ConditionsThatPreventsID = Convert.ToInt16(item.ConditionsThatPreventsReEmploymentID);

            _dal.UpdateProfileInfo(Userid, IDNumber, Surname, FirstName, Convert.ToString(DateOfBirth), (int)fkRaceID
                 , fkGenderID, CellNo, AlternativeNo, EmailAddress, UnitNo, ComplexName, StreetNo, StreetName, SuburbName
                 , City, PostalCode, (int)fkDisabilityID, NatureOfDisability, OtherNatureOfDisability, SACitizen
                 , (int)fkNationalityID, (int)fkProvinceID, (int)fkWorkPermitID, WorkPermitNo, pkCriminalOffenseID
                 , (int)fkLanguageForCorrespondenceID, TelNoDuringWorkingHours, MethodOfCommunicationID, CorrespondanceDetails
                 , Convert.ToInt32(1), (int)ProfessionallyRegisteredID, Convert.ToString(RegistrationDate), RegistrationNumber, RegistrationBody
                 , (int)PreviouslyEmployedPS, ReEmployment, PreviouslyEmployedDepartment, (int)DriversLicenseID, (int)MatricID,(int)ConditionsThatPreventsID);

            int profileID = 0;

            profileID = _dal.GetProfileID(User.Identity.GetUserId());

            if (postedCV != null && postedCV.ContentLength > 00)
            {
                var FileExt = System.IO.Path.GetExtension(postedCV.FileName).Substring(1);
                byte[] bytes;

                using (BinaryReader br = new BinaryReader(postedCV.InputStream))
                {
                    bytes = br.ReadBytes(postedCV.ContentLength);
                }

                //string fileName = Path.GetFileName(postedCV.FileName);
                string fileName = "Curriculum Vitae";
                string ContentType = postedCV.ContentType;
                var count = _db.Attachments.Where(x => x.ProfileID == profileID && x.fileName == fileName).Count();
                if (count == 0)
                {
                    _dal.AddAttachments(profileID, fileName, bytes, ContentType, System.IO.Path.GetExtension(postedCV.FileName));
                }
                else
                {
                    _dal.UpdateAttachments(profileID, fileName, bytes, ContentType, System.IO.Path.GetExtension(postedCV.FileName));
                }
             
            }

            if (postedID != null && postedID.ContentLength > 00)
            {

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/AddLanguages.cshtml
@model eRecruitment.Sita.Web.Models.Profile_LangauageModel
@{
    Layout = null;

    AjaxOptions details = new AjaxOptions
    {
        //Confirm = "Save these changes?",
        OnBegin = "OnBeginDetailMethod",
        OnFailure = "OnFailtureDetailMethod",
        OnSuccess = "OnSuccessDetailMethod",
        OnComplete = "OnCompleteDetailMethod"
    };
}
@{
    eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db =
        new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
    eRecruitmentDataAccess _dal = new eRecruitmentDataAccess();
}

@using (Ajax.BeginForm("AddLanguages", "CareerCenter", details))
{
    @Html.AntiForgeryToken()
    <div id="divDetailsStatus"></div>
    <div class="form-horizontal">

        <div class="form-group">
            <label for="inputLanguageName" class="col-sm-2 control-label">Language<span class="required">*</span></label>
            <div class="col-sm-10">
                @Html.DropDownList("languageID", new SelectList(ViewBag.Language, "LanguageID", "LanguageName", "--Select Language--"), new { @class = "form-control", required = "required", value = "" })
            </div>
        </div>
        <div class="form-group">
            <label for="inputSkillName" class="col-sm-2 control-label">Language Proficiency<span class="required">*</span></label>
            <div class="col-sm-10">
                @Html.DropDownList("LanguageProficiencyID", new SelectList(ViewBag.LanguageProficiency, "LanguageProficiencyID", "LanguageProficiency", "--Select Language Proficiency--"), new { @class = "form-control", required = "required", value = "" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="btnAddLanguage" class="btn btn-primary">Add</button>
                <input type="button" value="Cancel" class="btn btn-warning" onclick="getAddLanguageFunc()" />
            </div>
        </div>
    </div>
}
<script>

    function getAddLanguageFunc() {
        $("#getLanguageTable").load('@(Url.Action("getLanguages", "CareerCenter"))');
    }

    var isError = false;
    function OnBeginDetailMethod() {
        $("#divDetailsStatus").text("Loading ....");
    }

    function OnFailtureDetailMethod(error) {
        $("#errormessages").text(error.responseText);
        $("#divDetailsStatus").text("");
        isError = true;
    }

    function OnSuccessDetailMethod(data) {
        $("#divDetailsStatus").text("Processed the data Successfully!");
        $("#getLanguageTable").load('@(Url.Action("getLanguages", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
        isError = false;
    }

    function OnCompleteDetailMethod(data, status) {
        if (!isError) {
            $("#divDetailsStatus").text("Request status: " + status);
        }
    }
</script>

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/AddSkills.cshtml
@model eRecruitment.Sita.Web.Models.Skills_ProfileModel

@{
    Layout = null;

    AjaxOptions details = new AjaxOptions
    {
        //Confirm = "Save these changes?",
        OnBegin = "OnBeginDetailMethod",
        OnFailure = "OnFailtureDetailMethod",
        OnSuccess = "OnSuccessDetailMethod",
        OnComplete = "OnCompleteDetailMethod"
    };
}
@{
    eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db =
        new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
    eRecruitmentDataAccess _dal = new eRecruitmentDataAccess();
}


@using (Ajax.BeginForm("AddSkills", "CareerCenter", details))
{
    @Html.AntiForgeryToken()
    <div id="divDetailsStatus"></div>
    <div class="form-horizontal">
        <div class="form-group">
            <label for="inputSkillName" class="col-sm-2 control-label">Skill Name<span class="required">*</span></label>
            <div class="col-sm-10">
                @Html.DropDownList("SkillID", new SelectList(ViewBag.Skills, "skillID", "skillName", "--Select Skill--"), new { @class = "form-control", required = "required", value = "" })
            </div>
        </div>
        <div class="form-group">
            <label for="inputSkillName" class="col-sm-2 control-label">Skill Proficiency<span class="required">*</span></label>
            <div class="col-sm-10">
                @Html.DropDownList("SkillProficiencyID", new SelectList(ViewBag.SkillProficiency, "SkillProficiencyID", "SkillProficiency", "--Select Skill Proficiency--"), new { @class = "form-control", required = "required", value = "" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="btnAddSkill" class="btn btn-primary">Add</button>
                <input type="button" value="Cancel" class="btn btn-warning" onclick="getAddSkilllFunc()" />
            </div>
        </div>
    </div>
}

<script>

    function getAddSkilllFunc() {
        $("#getSkillTable").load('@(Url.Action("getSkills", "CareerCenter"))');
    }

    var isError = false;
    function OnBeginDetailMethod() {
        $("#divDetailsStatus").text("Loading ....");
    }

    function OnFailtureDetailMethod(error) {
        $("#errormessages").text(error.responseText);
        $("#divDetailsStatus").text("");
        isError = true;
    }

    function OnSuccessDetailMethod(data) {
        $("#divDetailsStatus").text("Processed the data Successfully!");
        $("#getSkillTable").load('@(Url.Action("getSkills", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
        isError = false;
    }

    function OnCompleteDetailMethod(data, status) {
        if (!isError) {
            $("#divDetailsStatus").text("Request status: " + status);
        }
    }
</script>

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/AddWorkHistory.cshtml
@model eRecruitment.Sita.Web.Models.WorkHistoryModel
@{
    Layout = null;

    AjaxOptions details = new AjaxOptions
    {
        //Confirm = "Save these changes?",
        OnBegin = "OnBeginDetailMethod",
        OnFailure = "OnFailtureDetailMethod",
        OnSuccess = "OnSuccessDetailMethod",
        OnComplete = "OnCompleteDetailMethod"
    };
}
@using (Ajax.BeginForm("AddWorkHistory", "CareerCenter", details))
{
    @Html.AntiForgeryToken()
    <div id="divDetailsStatus"></div>

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="inputCompanyNam" class="col-sm-2 control-label">Company Name<span class="required">*</span></label>
            <div class="col-sm-10">
                <input id="CompanyName" type="text" required="required" placeholder="Enter Company Name" name="companyName" data-required="1" class="form-control" ng-model="companyName" onKeyPress="return ValidateAlpha(event);" />
            </div>
        </div>
        <div class="form-group">
            <label for="inputJobTitle" class="col-sm-2 control-label">Job Title<span class="required">*</span></label>
            <div class="col-sm-10">
                <input id="JobTitle" type="text" required="required" placeholder="Enter Job Title" name="jobTitle" data-required="1" class="form-control" ng-model="jobTitle" onKeyPress="return ValidateAlpha(event);" />
            </div>
        </div>
        <div class="form-group">
            <label for="inputPositionHeld" class="col-sm-2 control-label">Position Held<span class="required">*</span></label>
            <div class="col-sm-10">
                <input id="PositionHeld" type="text" required="required" placeholder="Enter Position Held" name="positionHeld" data-required="1" class="form-control" ng-model="positionHeld" onKeyPress="return ValidateAlpha(event);" />
            </div>
        </div>
        <div class="form-group">
            <label for="inputDepartment" class="col-sm-2 control-label">Department<span class="required">*</span></label>
            <div class="col-sm-10">
                <input id="Department" type="text" required="required" placeholder="Enter Department" name="department" data-required="1" class="form-control" ng-model="department" onKeyPress="return ValidateAlpha(event);" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="date01">Start Date<span class="required">*</span></label>
            <div class="col-sm-10">
                <input type="date" class="form-control datepicker" id="startDate" required="required" name="startDate" ng-model="startDate">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="date01">End Date<span class="required">*</span></label>
            <div class="col-sm-10">
                <input type="date" class="form-control datepicker" id="endDate" required="required" name="endDate" ng-model="endDate">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="btnAddWorkHistory" class="btn btn-primary">Add</button>
                <input type="button" value="Cancel" class="btn btn-warning" onclick="getAddWorkFunc()" />
            </div>
        </div>
    </div>
}
<script>

     function getAddWorkFunc() {
         $("#getWorkTable").load('@(Url.Action("getWorkHistory", "CareerCenter"))');
     }

    var isError = false;
    function OnBeginDetailMethod() {
        $("#divDetailsStatus").text("Loading ....");
    }

    function OnFailtureDetailMethod(error) {
        $("#errormessages").text(error.responseText);
        $("#divDetailsStatus").text("");
        isError = true;
    }

    function OnSuccessDetailMethod(data) {
        $("#divDetailsStatus").text("Processed the data Successfully!");
        $("#getWorkTable").load('@(Url.Action("getWorkHistory", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
        isError = false;
    }

    function OnCompleteDetailMethod(data, status) {
        if (!isError) {
            $("#divDetailsStatus").text("Request status: " + status);
        }
    }
</script>

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/DeleteProfil_Langauage.cshtml
@model eRecruitment.Sita.Web.Models.CandidateLanguageProfileModel
@{
    Layout = null;
}
<h3>Are You Sure You Want To Delete This?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LanguageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LanguageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LanguageProficiency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LanguageProficiency)
        </dd>

    </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <button class="btn btn-warning" onclick="getDeleteLangFunc(@Model.profileLanguageID)" type="button" data-toggle="tooltip" data-placement="top"> Confirm</button> |
                <button class="btn btn-primary" onclick="getDeletePLFunc(@Model.profileLanguageID)" type="button" data-toggle="tooltip" data-placement="top"> Back to List</button>
            </div>
        }
</div>

<script>
    function getDeletePLFunc(data) {
        $("#getLanguageTable").load('@(Url.Action("getLanguages", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
    }

    function getDeleteLangFunc(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteProfile_Langauage", "CareerCenter")'+ '?id=' + id,
            contentType: false,
            processData: false,
            data: { "id": id },
            success: function (data) {
                $("#getLanguageTable").load('@(Url.Action("getLanguages", "CareerCenter"))');
                },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                $("#divDetailsStatus").text(err);
            }
        });

        function OnSuccessDetailMethod(data) {
            $("#divDetailsStatus").text("Processed the data Successfully!");
            closemodal();
            $("#getLanguageTable").load('@(Url.Action("getLanguages", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
            isError = false;
        }

    }
</script>

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/DeleteSkill_Profile.cshtml
@model eRecruitment.Sita.Web.Models.CandidateSkillsProfileModel
@{
    Layout = null;
}
<h3>Are You Sure You Want To Delete This?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.skillName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skillName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SkillProficiency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SkillProficiency)
        </dd>

    </dl>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <button class="btn btn-warning" onclick="getDeleteSkiFunc(@Model.skillsProfileID)" type="button" data-toggle="tooltip" data-placement="top"> Confirm</button> |
        <button class="btn btn-primary" onclick="getDeleteSPFunc(@Model.skillsProfileID)" type="button" data-toggle="tooltip" data-placement="top"> Back to List</button>
    </div>
}
</div>

<script>
    function getDeleteSPFunc(data) {
        $("#getSkillTable").load('@(Url.Action("getSkills", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
    }

    function getDeleteSkiFunc(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteSkills_Profile", "CareerCenter")'+ '?id=' + id,
            contentType: false,
            processData: false,
            data: { "id": id },
            success: function (data) {
                $("#getSkillTable").load('@(Url.Action("getSkills", "CareerCenter"))');
                },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                $("#divDetailsStatus").text(err);
            }
        });

        function OnSuccessDetailMethod(data) {
            $("#divDetailsStatus").text("Processed the data Successfully!");
            closemodal();
            $("#getSkillTable").load('@(Url.Action("getSkills", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
            isError = false;
        }

    }
</script>

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/EducationDelete.cshtml
@model eRecruitment.Sita.Web.Models.CandidateEducationModel
@{
    Layout = null;
}
<h3>Are You Sure You Want To Delete This?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.institutionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.institutionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qualificationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qualificationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QualificationTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QualificationTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.certificateNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.certificateNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.endDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.endDate)
        </dd>
    </dl>

   @using (Html.BeginForm())
   {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <button class="btn btn-warning" onclick="getDeleteEduFunc(@Model.qualificationID)" type="button" data-toggle="tooltip" data-placement="top"> Confirm</button> |
        <button class="btn btn-primary" onclick="getDeleteEFunc(@Model.qualificationID)" type="button" data-toggle="tooltip" data-placement="top"> Back to List</button>
    </div>
   }
</div>
<script>
    function getDeleteEFunc(data) {
        $("#getEduTable").load('@(Url.Action("getEducation", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
    }

    function getDeleteEduFunc(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteEducation", "CareerCenter")'+ '?id=' + id,
            contentType: false,
            processData: false,
            data: { "id": id },
            success: function (data) {
                 $("#getEduTable").load('@(Url.Action("getEducation", "CareerCenter"))');
                },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                $("#divDetailsStatus").text(err);
            }
        });

        function OnSuccessDetailMethod(data) {
            $("#divDetailsStatus").text("Processed the data Successfully!");
            closemodal();
            $("#getEduTable").load('@(Url.Action("getEducation", "CareerCenter", null, Request.Url.Scheme))?id=' + data);
            isError = false;


        }

    }
</script>

FrontendApplication/eRecruitment.Sita.Web/Views/CareerCenter/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>