FrontendApplication/eRecruitment.Sita.Web/Controllers/VacancyController.cs
using eRecruitment.Sita.Web.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace eRecruitment.Sita.Web.Controllers
{

  
    public class VacancyController : Controller
    {
        eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db = new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
        eRecruitmentDataAccess _dal = new eRecruitmentDataAccess();
        //eRecruitment.Sita.Web.Notifications.SendNotification notify = new eRecruitment.Sita.Web.Notifications.SendNotification();
        Notification notify = new Notification();
            
        // GET: Vacancy
        [Authorize]
        public ActionResult Index()
        {
            string userid = User.Identity.GetUserId();
            ViewBag.VacancyList = _dal.GetVacancyListByUser(userid);
            ViewBag.RetractList = _dal.GetRetractReasonList();
            ViewBag.WithdrawalList = _dal.GetWithdrawalReasonList();

            return View();
        }

        public JsonResult GetVacancyQuestionBank(string list)
        {
            try
            {
                dynamic rec = JsonConvert.DeserializeObject(list);
                int vid = Convert.ToInt16(rec.VID);
                var data = _dal.GetVacancyQuestionBanksListByID(Convert.ToInt16(vid));
                ViewBag.VacancyQuetionBanks = data.ToList();
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message, results = "" }, JsonRequestBehavior.AllowGet);
            }

        }
     
        public JsonResult GetSalaryRangeByID(string vid)
        {
            try
            {
                //dynamic data = JsonConvert.DeserializeObject(list);
                //int PID = Convert.ToInt16(data);
                //var data = _dal.GetVacancyProfile(Convert.ToInt16(vid));
                var data = _dal.GetSalaryRange(Convert.ToInt16(vid));
                return Json(data, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message, results = "" }, JsonRequestBehavior.AllowGet);
            }
        }

        //get all Approve Vacancy
        [Authorize]
        public ActionResult ApproveVacancy()
        {
            string userid = User.Identity.GetUserId();
            ViewBag.ApprovedVacancy = _dal.GetApprovedVacancyList(userid);
            return View();
        }
        //Download Vacancy Ad
        public ActionResult DownloadVacancyAd(int id)
        {
            var data = _db.sp_GetVacancyAdDetail(id).FirstOrDefault();

            using (System.IO.MemoryStream memoryStream = new System.IO.MemoryStream())
            {

                Document document = new Document(PageSize.A4, 10, 10, 10, 10);
                //Document document = new Document(PageSize.A4.Rotate(), 10, 10, 10, 10);
                Font courier = new Font(Font.FontFamily.HELVETICA, 9f);

                PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);
                document.Open();
                //document.Add(new Paragraph("\n"));

                //var logo = iTextSharp.text.Image.GetInstance(Server.MapPath("~/Content/dist/img/sita.png"));

                var logo = Image.GetInstance((byte[])data.FileData.ToArray());
                logo.Alignment = Element.ALIGN_CENTER;
                logo.ScaleToFit(120f, 80f);

                document.Add(logo);
                //document.SetPageSize(iTextSharp.text.PageSize.A4.Rotate());

                BaseFont bf = BaseFont.CreateFont(BaseFont.TIMES_ROMAN, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
                iTextSharp.text.Font font = new iTextSharp.text.Font(bf, 10, iTextSharp.text.Font.NORMAL);

                ////Insert Image
                //string imagepath = Server.MapPath("img");
                //Image gif = Image.GetInstance(imagepath + "/eclogoAIM.png");
                //gif.Alignment = Element.ALIGN_LEFT;
                ////Resize image depend upon your need
                //gif.ScaleToFit(250f, 200f);
                ////Give space before image
                //gif.SpacingBefore = 10f;
                ////Give some space after the image
                //gif.SpacingAfter = 1f;
                //document.Add(gif);
                ////End Image

                Paragraph paraHead = new Paragraph("VACANCY ADVERTISEMENT");
                paraHead.Alignment = Element.ALIGN_CENTER;
                paraHead.Font = FontFactory.GetFont("dax-black", 10, Font.BOLD);
                //cellVacancyPurpose.BackgroundColor = BaseColor.LIGHT_GRAY;

                document.Add(paraHead);
                document.Add(new Paragraph("\n"));

                PdfPTable table = new PdfPTable(2);

                //PdfPCell cell = new PdfPCell(new Phrase("Vacancy Information Download"));
                PdfPCell cell = new PdfPCell(new Phrase("Vacancy Information Download",font));
                cell.Colspan = 2;
                cell.HorizontalAlignment = Element.ALIGN_CENTER;
                cell.BackgroundColor = BaseColor.LIGHT_GRAY;
                cell.Border = 0; //Added this for testing
                table.AddCell(cell);

                PdfPCell emptyCell = new PdfPCell(new Phrase(" ",font));
                emptyCell.Colspan = 2;
                emptyCell.Border = 0;
                table.AddCell(emptyCell);

                //Reference Number
                //table.AddCell("Reference Number:");
                //table.AddCell(data.ReferenceNo);

                PdfPCell cellReferenceNo = new PdfPCell(new Phrase("Reference Number:", font));
                cellReferenceNo.Colspan = 1;
                cellReferenceNo.HorizontalAlignment = Element.ALIGN_LEFT;
                //cellReferenceNo.BackgroundColor = BaseColor.LIGHT_GRAY;
                table.AddCell(cellReferenceNo);

                PdfPCell cellReferenceNoContent = new PdfPCell(new Phrase(data.ReferenceNo.ToString(), font));
                cellReferenceNoContent.Colspan = 1;
                cellReferenceNoContent.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                table.AddCell(cellReferenceNoContent);

                PdfPCell cellBPSNo = new PdfPCell(new Phrase("BPS Vacancy Number:", font));
                cellBPSNo.Colspan = 1;
                cellBPSNo.HorizontalAlignment = Element.ALIGN_LEFT;
                //cellReferenceNo.BackgroundColor = BaseColor.LIGHT_GRAY;
                table.AddCell(cellBPSNo);

                PdfPCell cellBPSNoContent = new PdfPCell(new Phrase(data.VacancyNo.ToString(), font));
                cellBPSNoContent.Colspan = 1;
                cellBPSNoContent.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                table.AddCell(cellBPSNoContent);


                //Job Title
                PdfPCell cellJobTitle = new PdfPCell(new Phrase("Job Title:", font));
                cellJobTitle.Colspan = 1;
                cellJobTitle.HorizontalAlignment = Element.ALIGN_LEFT;
                table.AddCell(cellJobTitle);

                PdfPCell cellJobTitleContent = new PdfPCell(new Phrase(data.JobTitle.ToString(), font));
                cellJobTitleContent.Colspan = 1;
                cellJobTitleContent.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                table.AddCell(cellJobTitleContent);


                //Job Level
                PdfPCell cellJobLevel = new PdfPCell(new Phrase("Job Level:", font));
                cellJobLevel.Colspan = 1;
                cellJobLevel.HorizontalAlignment = Element.ALIGN_LEFT;
                table.AddCell(cellJobLevel);

                PdfPCell cellJobLevelContent = new PdfPCell(new Phrase(data.JobLevel.ToString(), font));
                cellJobLevelContent.Colspan = 1;
                cellJobLevelContent.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                table.AddCell(cellJobLevelContent);


                //Vacancy Type
                PdfPCell cellVacancyType = new PdfPCell(new Phrase("Vacancy Type:", font));
                cellVacancyType.Colspan = 1;
                cellVacancyType.HorizontalAlignment = Element.ALIGN_LEFT;
                table.AddCell(cellVacancyType);

                PdfPCell cellVacancyTypeContent = new PdfPCell(new Phrase(data.VacancyTypeName.ToString(), font));
                cellVacancyTypeContent.Colspan = 1;
                cellVacancyTypeContent.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                table.AddCell(cellVacancyTypeContent);

                //Salary Range
                PdfPCell cellSalaryRange = new PdfPCell(new Phrase("Salary Range:", font));
                cellSalaryRange.Colspan = 1;
                cellSalaryRange.HorizontalAlignment = Element.ALIGN_LEFT;
                table.AddCell(cellSalaryRange);

                PdfPCell cellSalaryRangeContent = new PdfPCell(new Phrase(data.Salary.ToString(), font));
                cellSalaryRangeContent.Colspan = 1;
                cellSalaryRangeContent.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                table.AddCell(cellSalaryRangeContent);

                //Organisation
                PdfPCell cellOrganisationName = new PdfPCell(new Phrase("Organisation Name:", font));
                cellOrganisationName.Colspan = 1;
                cellOrganisationName.HorizontalAlignment = Element.ALIGN_LEFT;
                table.AddCell(cellOrganisationName);

                PdfPCell cellOrganisationNameContent = new PdfPCell(new Phrase(data.OrganisationName.ToString(), font));
                cellOrganisationNameContent.Colspan = 1;

FrontendApplication/eRecruitment.Sita.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FrontendApplication/eRecruitment.Sita.Web/Views/Home/Blank.cshtml
@{
    ViewBag.Title = "Blank";
}

    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>
    <!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
</section>
<div>
    <pre>
           {{StatusData | json}}
    </pre>
    
    <pre>
           {{EmploymentType | json}}
    </pre>
    <select name="LanguageID" class="form-control" style="width:300px" id="LanguageID" ng-model="LanguageID" ng-change="GetStatusTest()">
        <option ng-repeat="m in StatusData" value="{{m.StatusID}}">{{m.StatusDescription}}</option>
        @*<option ng-selected="1">1</option>*@
    </select>
</div>
<!-- /.content -->

FrontendApplication/eRecruitment.Sita.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<button ng-click="GetCandidateEducationData()">Get Data</button>

<pre>
{{EducationListData | json}}
</pre>

FrontendApplication/eRecruitment.Sita.Web/Views/Home/Index.cshtml
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dashboard
        @*<small>Control panel</small>*@
        <small>&nbsp;</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@ViewBag.TotalVacancy</h3>
                    <p>Total Vacancies</p>
                </div>
                <div class="icon">
                    <i class="ion ion-navicon-round"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    @*<h3>53<sup style="font-size: 20px">%</sup></h3>*@
                    <h3>@ViewBag.TotalApproved</h3>
                    <p>Approved</p>
                </div>
                <div class="icon">
                    <i class="ion ion-paper-airplane"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>@ViewBag.TotalRejected</h3>
                    <p>Rejected</p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-cancel"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>@ViewBag.TotalWithdrawn</h3>
                    <p>Withdrawn</p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-download"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <div class="row">
        <div class="col-md-12">
            <img src="@Url.Action("CreateBarMonth")" alt="" />
        </div>
    </div>
   

    <!-- /.row (main row) -->
</section>
<!-- /.content -->

<div class="row">
    @*<div class="col-md-6">
        <div class="box box-success">
            <img src="@Url.Action("CreatePie")" alt="Bar Chart using MVC" />
        </div>
    </div>*@
    @*<div class="col-md-6">
        <div class="box box-primary">
            <img src="@Url.Action("CreateBar")" alt="Bar Chart using MVC" />
        </div>
    </div>*@
    @*<div class="col-md-6">
        <div class="box box-success">
            <img src="@Url.Action("CreatePieGender")" alt="Pie Chart using MVC" />
        </div>
    </div>*@
    @*<div class="col-md-6">
        <div class="box box-primary">
            <img src="@Url.Action("CreateLine")" alt="Pie Chart using MVC" />
        </div>
    </div>*@
</div>

FrontendApplication/eRecruitment.Sita.Web/Views/Home/Jobs.cshtml
@{
  ViewBag.Title = "Blank";
}
@using System.Data.Linq
@{
  eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext _db =
      new eRecruitment.Sita.Web.App_Data.DAL.eRecruitmentDataClassesDataContext();
}
<section class="content-header">
  <h1>
    Active Vacancies
    <small>your career begins here</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="~/Home/Jobs"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="~/Home/Jobs">Browse Jobs</a></li>
    <li class="active">Active Vacancies</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <!-- Default box -->
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Browse All Active Jobs</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove" disabled data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i>
        </button>
      </div>
    </div>


    <div class="box-body">
      @{
        //DateTime currentdate = Convert.ToDateTime(DateTime.Now.ToString("d"));
        var appvac = _db.tblVacancies.Where(h => h.ClosingDate >= Convert.ToDateTime(DateTime.Now.ToString("d")) && h.StatusID == 3).Select(h => h.ID).Count();

        if (appvac > 0)
        {
          var comp = (from a in _db.lutOrganisations
                      join b in _db.tblVacancies on a.OrganisationID equals b.OrganisationID
                      where b.ClosingDate >= Convert.ToDateTime(DateTime.Now.ToString("d")) && b.StatusID == 3
                      select new
                      {
                        OrganisationID = a.OrganisationID,
                        OrganisationCode = a.OrganisationCode,
                        OrganisationName = a.OrganisationName,
                        fileName = a.fileName,
                        fileData = a.fileData,
                        contentType = a.contentType
                      }).Distinct();

          //var data = _db.lutOrganisations.ToList();
          var base64 = (string)null;
          if (comp != null)
          {
            foreach (var d in comp)
            {
              base64 = Convert.ToBase64String(d.fileData.ToArray());
              var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
              string orgCD = d.OrganisationCode;
              string orgName = d.OrganisationName;
              int orgID = d.OrganisationID;

              int jobcount = _db.tblVacancies.Where(x => x.OrganisationID == orgID && x.StatusID == 3 && x.ClosingDate >= Convert.ToDateTime(DateTime.Now.ToString("d"))).Count();


              <div class="dl-horizontal">
                <div class="col-md-4">
                  <!-- small box -->
                  <div class="small-box bg-default">
                    <div class="inner">
                      <h3 style="color:blue">@*@orgCD*@</h3>
                      <img src="@imgSrc" style="width:auto;height:114px;opacity: 0.4;filter: alpha(opacity=40);" class="img-responsive" /><br />
                      <p style="color:black">@orgName (@jobcount)</p>
                    </div>
                    <div class="icon">
                      @*<i class="ion ion-bag">

                        </i>*@
                      <img src="~/Content/dist/img/salogo.png" style="height:100px;opacity: 0.4;filter: alpha(opacity=40);" />
                    </div>


                    @*<a href='@Url.Action("BrowseVacancy", "Vacancy", new { id = @orgID})' class="small-box-footer"> Browse Jobs</a>*@
                    <a href='@Url.Action("BrowseVacancy", "Vacancy", new { id = @orgID })' class="small-box-footer" style="color:black">Browse Jobs <i class="fa fa-arrow-circle-right"></i></a>


                  </div>
                </div>

                @*<div class="col-md-4 vertical">
                      <img src="@imgSrc" style="width:150px" class="img-responsive" /><br />
                  </div>*@
              </div>



            }
          }
        }
        else
        {
          <div class="dl-horizontal">
            <div class="col-md-12">
              No Jobs To Apply For
            </div>
          </div>
        }


      }
    </div>

    <!-- /.box-body -->
    <div class="box-footer">

    </div>
    <!-- /.box-footer-->
  </div>
  <!-- /.box -->
</section>

<!-- /.content -->

FrontendApplication/eRecruitment.Sita.Web/Views/Home/LogOff.cshtml
@{
    ViewBag.Title = "LogOff";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LogOff</h2>

FrontendApplication/eRecruitment.Sita.Web/Views/Home/StartupPage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <style>
        .center {
            margin: auto;
            width: 90%;
            padding: 70px;
            align-content: center;
            position: fixed;
            left: 23%;
        }
    </style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SITA | eRecruitment</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-blue layout-top-nav">
    <div class="row">
        <div class="col-xs-4 col-md-2">
            <div class="form-group">
                <div class="image">
                    <img src="~/Content/Images/SITALogo.PNG" height="110" width="150" />
                </div>
            </div>
        </div>

        @*<div class="col-xs-4 col-md-2 col-md-push-3">
                <div class="form-group">
                    <div class="image pull-center">
                        <img src="~/Content/Images/SITALogo.PNG" height="110" width="200"/>
                    </div>
                </div>
            </div>*@

        <div class="col-xs-6 col-md-6 col-md-push-4">
            <div class="form-group">
                <div class="image pull-right">
                    <img src="~/Content/Images/SAFlag.png" height="100" width="125">
                </div>
            </div>
        </div>

    </div>

    <div class="wrapper">
        <header class="main-header">
            <nav class="navbar navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <a href="" class="navbar-brand"><b>E</b>-Recruitment</a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                        <ul class="nav navbar-nav"></ul>

                    </div>
                    <!-- /.navbar-collapse -->
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Messages: style can be found in dropdown.less-->
                        </ul>
                    </div>
                    <!-- /.navbar-custom-menu -->
                </div>
                <!-- /.container-fluid -->
            </nav>
        </header>



        <!-- Full Width Column -->
        <div class="content-wrapper">
            <br>
            <br>
            <div class="container">
                <div class="center">
                    <div class="col-md-6">
                        <div class="box box-success">
                            <div class="box-header with-border">
                                <h3 class="box-title">Sign In Option</h3>
                            </div>
                            <!-- /.box-header -->
                            <!-- form start -->
                            @using (Html.BeginForm("StartupPage", "Home", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
                            {
                                <div class="box-body">
                                    <div class="form-group">
                                        @*<label for="exampleInputEmail1">Email address</label>*@
                                        <select name="signInOptions" required class="form-control select2" style="width: 100%;">
                                            <option value="" selected="selected">--Please Select--</option>
                                            <option value="1">Citizen</option>
                                            @*<option value="2">Official</option>*@
                                        </select>
                                    </div>
                                </div>
                                <!-- /.box-body -->
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                                @*</form>*@
                            }
                        </div>
                    </div>
                    @*<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img src="~/Images/Image.png" alt="First slide">
                                    <div class="carousel-caption">
                                        First Slide
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="http://placehold.it/900x500/3c8dbc/ffffff&text=I+Love+Bootstrap" alt="Second slide">
                                    <div class="carousel-caption">
                                        Second Slide
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="http://placehold.it/900x500/f39c12/ffffff&text=I+Love+Bootstrap" alt="Third slide">
                                    <div class="carousel-caption">
                                        Third Slide
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="fa fa-angle-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="fa fa-angle-right"></span>
                            </a>
                        </div>*@
                </div>
            </div>
            <!-- /.container -->

        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.4.0
                </div>
                <strong>Copyright &copy; 2018 <a href="https://www.sita.co.za">SITA</a>.</strong> All rights
                reserved.
            </div>
            <!-- /.container -->
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Content/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>
</body>
</html>